### ISSUE TITLE
Broken in 0.12

### ISSUE THREAD

**Issue by Enivex** [T1mVo/shadowed#1]
```typ
#import "@preview/shadowed:0.1.0": shadowed

#set par(justify: true)

#shadowed(radius: 4pt, inset: 12pt)[
    #lorem(50)
]
```
now renders as
![image](https://github.com/user-attachments/assets/323d729c-e0ac-44ae-8a50-ad35072700bf)

instead of

![image](https://github.com/user-attachments/assets/a6cbfa37-269a-45a9-a391-028f3f62b200)

**Comment by T1mVo** [comment]
Its already fixed [here](https://github.com/T1mVo/shadowed/tree/typst-v0.12.0). I will merge it when Typst 0.12.0 releases as it breaks compatibility with 0.11.

**Comment by T1mVo** [comment]
Fixed with 0.1.1

**Comment by Enivex** [comment]
@T1mVo It's still broken when there's not enough content to get a full line

```
#import "@preview/shadowed:0.1.1": shadowed

#set par(justify: false)

#shadowed(radius: 4pt, inset: 12pt)[
    #lorem(5)
]
```
renders as
![image](https://github.com/user-attachments/assets/cf28d556-4408-4268-9c14-3b2a720c99cc)
